name: Tags

permissions:
  contents: write
  actions: read


on:
  push:
    branches:
      - main          # Trigger on version tags like v1.0.0

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_ACTION }}
        run: |
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG
