name: Build and Publish macOS Electron App

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_ACTION }}
        run: |
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG

  build-and-publish:
    needs: auto-tag
    runs-on: macos-latest
    env:
      CSC_LINK: ${{ secrets.APPLE_SIGNING_CERTIFICATE_BASE64 }}
      CSC_KEY_PASSWORD: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
      APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Decode and import Apple certificate to keychain
        run: |
          echo "$CSC_LINK" | base64 --decode > mac_certs.p12
          security create-keychain -p "" build.keychain
          security import mac_certs.p12 -k ~/Library/Keychains/build.keychain -P "$CSC_KEY_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      - name: Decode Apple API key for notarization
        run: echo "$APPLE_API_KEY_BASE64" | base64 --decode > AuthKey.p8

      - name: Build and publish Electron app (macOS) with notarization using token
        run: |
          # Configure environment variables for electron-builder
          export CSC_IDENTITY_AUTO_DISCOVERY=true
          export CSC_KEYCHAIN=~/Library/Keychains/build.keychain
          export NOTARIZE_APPLE_API_KEY_PATH=$(pwd)/AuthKey.p8
          export NOTARIZE_APPLE_API_KEY_ID=$APPLE_API_KEY_ID
          export NOTARIZE_APPLE_API_ISSUER_ID=$APPLE_API_ISSUER_ID

          npm run build:mac -- --publish=always
