name: Build and Publish macOS Electron App

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_ACTION }}
        run: |
          TAG="v$VERSION"
          git tag $TAG
          git push origin $TAG

  build-and-publish:
    needs: auto-tag
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # Décode le certificat base64
      - name: Prepare certificate
        env:
          CSC_CONTENT: ${{ secrets.MAC_CERTIFICATE }}
        run: |
          echo "$CSC_CONTENT" | base64 --decode > certificate.p12

      - name: Build and publish Electron app (macOS)
        run: npm run build:mac -- --publish=always
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ./certificate.p12
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
